### ISSUE TITLE
Adding a layer #2 guide section

### ISSUE THREAD

**Issue by ricardomatias** [zeropaper/visual-fiha#43]
The tooltip should not be on top of the dropdown, that appears once you try to choose which kind of layer you want to create.

![screen shot 2017-04-08 at 11 10 37](https://cloud.githubusercontent.com/assets/8850708/24827540/093c2274-1c4c-11e7-8b65-c347186c40a8.png)

**Comment by zeropaper** [comment]
Yeah... the tour tool very simple/naive for now.
It has some kind of position detection mechanism 
but it would be good to have a way to specify where the tooltip is attached with the following options:
 - top
 - top-left
 - top-right
 - bottom
 - bottom-left
 - bottom-right
 - left
 - left-top
 - left-bottom
 - right
 - right-top
 - right-bottom
